#!/usr/bin/env python3
"""
Generate PWM ramp tables for perception-corrected LED brightness.

Supports:
  - Linear ramp with gamma correction (default)
  - Sine wave with gamma correction (--sine)

Usage:
    python generate_ramp_table.py --bits 13 > ../include/ramp_table_13bit.h
    python generate_ramp_table.py --bits 13 --sine > ../include/ramp_sine_13bit.h
"""

import argparse
import math
import sys

def generate_gamma_table(size: int, max_val: int, gamma: float) -> list[int]:
    """Generate linear ramp with gamma correction."""
    table = []
    for i in range(size):
        normalized = i / (size - 1) if size > 1 else 0
        corrected = pow(normalized, gamma)
        duty = int(round(corrected * max_val))
        table.append(duty)
    return table

def generate_sine_table(size: int, max_val: int, gamma: float) -> list[int]:
    """Generate sine wave with gamma correction for perception."""
    table = []
    for i in range(size):
        # Sine wave: 0 to 1 to 0 over full cycle
        # Use (1 - cos(x)) / 2 for smooth 0->1->0 transition
        angle = (i / size) * 2 * math.pi
        normalized = (1 - math.cos(angle)) / 2
        # Apply gamma correction for perception
        corrected = pow(normalized, gamma)
        duty = int(round(corrected * max_val))
        table.append(duty)
    return table

def print_c_header(table: list[int], bits: int, gamma: float, is_sine: bool):
    """Print the table as a C header file."""
    max_duty = (1 << bits) - 1
    size = len(table)
    mode = "sine" if is_sine else "ramp"
    
    # Gamma suffix for naming (e.g., g22 for gamma 2.2)
    gamma_str = f"g{int(gamma * 10)}"
    
    guard_name = f"PWM_{mode.upper()}_{bits}BIT_{gamma_str.upper()}_H"
    table_name = f"pwm_{mode}_table_{bits}bit_{gamma_str}"
    
    # Color suitability based on gamma
    if gamma <= 2.2:
        color_note = "Suitable for: White, warm white, red LEDs"
    elif gamma <= 2.5:
        color_note = "Suitable for: Green, amber LEDs"
    else:
        color_note = "Suitable for: Blue, cool white LEDs (higher gamma for blue sensitivity)"
    
    print(f"""/*
 * Auto-generated PWM {mode} table for perception-corrected LED brightness.
 * Generated by: scripts/generate_ramp_table.py --bits {bits} --gamma {gamma} {"--sine" if is_sine else ""}
 *
 * Configuration:
 *   Mode: {mode}
 *   Resolution: {bits}-bit (max duty = {max_duty})
 *   Table size: {size} entries
 *   Gamma: {gamma}
 *
 * {color_note}
 *
 * Gamma reference:
 *   2.0-2.2: Standard (white/red LEDs)
 *   2.3-2.5: Mid-range (green/amber LEDs)
 *   2.6-3.0: High (blue LEDs, human eye less sensitive to blue)
 */

#ifndef {guard_name}
#define {guard_name}

#include <stdint.h>

#define PWM_{mode.upper()}_{bits}BIT_{gamma_str.upper()}_SIZE {size}
#define PWM_{mode.upper()}_{bits}BIT_{gamma_str.upper()}_MAX_DUTY {max_duty}

static const uint16_t {table_name}[{size}] = {{""")
    
    for i in range(0, len(table), 16):
        line_values = table[i:i+16]
        line_str = ", ".join(f"{v:5d}" for v in line_values)
        if i + 16 < len(table):
            print(f"    {line_str},")
        else:
            print(f"    {line_str}")
    
    print(f"""}};

#endif /* {guard_name} */""")

def main():
    parser = argparse.ArgumentParser(description='Generate PWM ramp/sine table')
    parser.add_argument('--bits', type=int, default=13, 
                        help='PWM resolution in bits (default: 13)')
    parser.add_argument('--steps', type=int, default=256,
                        help='Number of table entries (default: 256)')
    parser.add_argument('--gamma', type=float, default=2.8,
                        help='Gamma correction factor (default: 2.8)')
    parser.add_argument('--sine', action='store_true',
                        help='Generate sine wave instead of linear ramp')
    args = parser.parse_args()
    
    max_duty = (1 << args.bits) - 1
    
    if args.sine:
        table = generate_sine_table(args.steps, max_duty, args.gamma)
        mode = "sine"
    else:
        table = generate_gamma_table(args.steps, max_duty, args.gamma)
        mode = "ramp"
    
    print(f"/* Generated {args.bits}-bit {mode} table, gamma={args.gamma} */", file=sys.stderr)
    
    print_c_header(table, args.bits, args.gamma, args.sine)

if __name__ == "__main__":
    main()
